- name: Setup OpenLDAP Server
  hosts: openLDAP_server
  become: yes
  vars:
    ldap_domain: "mydomain.org"
    ldap_org: "MyOrg"
    ldap_dn: "dc=mydomain,dc=org"
    ldap_root_pass: "SuperSecret123"

    my_groups:
      - { name: 'devs', gid: 5001 }
      - { name: 'admin', gid: 5002 }
    my_users:
      - { uid: 'dmitPetrov', name: 'Dmitry', sn: 'Petrov', uid_num: 10001, gid_num: 5002, password: 'password123' }
      - { uid: 'ivIvanov', name: 'Ivan', sn: 'Ivanov', uid_num: 10002, gid_num: 5001, password: 'password456' }

  tasks:
  - name: Install openLDAP packages
    apt:
      name:
        - slapd
        - ldap-utils
        - python3-ldap
      state: present
      update_cache: yes

  - name: Install debconf-utils for configuration
    apt:
      name: debconf-utils
      state: present

  - name: Configurate slapd via debconf
    debconf:
      name: slapd
      question: "{{ item.q }}"
      value: "{{ item.v }}"
      vtype: "{{ item.t }}"
    loop:
      - {q: 'slapd/internal/admin_password', v: "{{ ldap_root_pass }}", t: 'password'}
      - {q: 'slapd/domain', v: "{{ ldap_domain }}", t: 'string' }

  - name: Generate LDIF from template
    template:
      src: templates/data.ldif.j2
      dest: /tmp/setup.ldif

  - name: Import ldif to openLDAP
    shell: "ldapadd -x -D 'cn=admin,dc=mydomain,dc=org' -w {{ ldap_root_pass }} -f /tmp/setup.ldif"
    register: ldap_result
    failed_when: "ldap_result.rc != 0 and 'Already exists' not in ldap_result.stderr"
    changed_when: "ldap_result.rc == 0"
